---

- name: Add ENV vars in cron.d file (REDHAD)
  cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    user: "{{ item.user }}"
    env: yes
    cron_file: "{{ item.filename }}"
    state: present
  loop: "{{ cron_env | default([]) }}"
  become: true
  when: cron_env is defined

- name: Add cron jobs (RedHat)
  cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute }}"
    job: "{{ item.job }}"
    user: "{{ item.user }}"
    cron_file: "{{ item.filename }}"
    backup: true
  loop: "{{ cron_jobs | default([]) }}"
  become: true
  when: cron_jobs is defined

- name: Set a universal Apache policy (RedHat)
  command: "setsebool -P httpd_unified 1"
  become: true
  changed_when: false

- name: Ensure nagios home directory has search permissions on (RedHat)
  file:
    path: "{{ nagios_registered.home }}"
    state: directory
    mode: "0701"
  become: true

- name: Ensure html directory exists under nagios home directory (RedHat)
  file:
    path: "{{ nagios_registered.home }}/{{ item }}"
    state: directory
    owner: nagios
    group: nagios
    mode: "0755"
  loop:
    - "html"
  become: true

- name: Install policycoreutils-python (RedHat)
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ core_utils }}"
  become: true

# semanage fcontext -a -t httpd_sys_content_t "/var/spool/nagios/html(/.*)?"
# /etc/selinux/targeted/contexts/files/file_contexts.local
- name: Set selinux policy for directories (RedHat)
  sefcontext:
   target: "{{ item.target }}(/.*)?"
   setype: "{{ item.setype }}"
   reload: True
   state: present
  become: true
  with_items:
  - { target: "{{ nagios_registered.home }}/html", setype: "httpd_sys_content_t" }

- name: Apply new SELinux file context to filesystem (RedHat)
  command: "restorecon -irv {{ item }}"
  loop:
    - "{{ nagios_registered.home }}/html"
  become: true