---

- name: Register static files to be copied
  find:
    paths: "{{ inventory_dir }}/files/monservers"
    file_type: file
    recurse: yes
  register: static_files
  ignore_errors: yes
  delegate_to: 127.0.0.1

- name: Display files to be copied
  debug:
    msg: "/{{ item.path | regex_replace('(.*)[/]files[/]monservers[/](.*)', '\\2') }}"
    verbosity: 1
  loop: "{{ static_files.files }}"
  loop_control:
    label: "Copied file {{ item.path }}"
  when: static_files is defined

- name: Copy static files
  copy:
    src: "{{ item.path }}"
    dest: "/{{ item.path | regex_replace('(.*)[/]files[/]monservers[/](.*)', '\\2') }}"
    force: yes
    owner: root
    mode: 0664
    backup: true
  loop: "{{ static_files.files }}"
  loop_control:
    label: "Added file /{{ item.path | regex_replace('(.*)[/]files[/]monservers[/](.*)', '\\2') }}"
  become: yes
  ignore_errors: yes
  when: static_files is defined
