---

######## Create postgresql plugin
- name: "Task block: Create postgresql plugin"
  block:
  - name: create postresql plugin dir with parent directories
    file:
      path: "{{ keycloak_home }}/modules/system/layers/keycloak/org/postgresql/main"
      state: directory
  - name: Download postgresql JDBC driver
    get_url:
      url: "https://jdbc.postgresql.org/download/{{ keycloak_postgresql_jar_name }}"
      dest: "{{ keycloak_home }}/modules/system/layers/keycloak/org/postgresql/main"
  - name: Installing postgresql plugin
    template:
      src: templates/module.xml.j2
      dest: "{{ keycloak_home }}/modules/system/layers/keycloak/org/postgresql/main/module.xml"
  become: yes
  tags: "keycloak:install:postgresql_plugin"

######## Install template standalone-ha.xml

- name: Installing keycloak configuration (standalone-ha.xml)
  template:
    mode: 0600
    src: "templates/{{ keycloak_version }}/standalone-ha.xml.j2"
    dest: "{{ keycloak_home }}/standalone/configuration/standalone-ha.xml"
  become: yes
  tags: "keycloak:install:standaloneha"

##### Set keycloak working dir and logs writable for service user
- name: "Setting standalone folder writable for user: {{ keycloak_service_user }} - where it's internal temporary files are created"
  file:
    dest: "{{ keycloak_home }}/standalone"
    owner: "{{ keycloak_service_user }}"
    group: "{{ keycloak_service_user }}"
    recurse: yes
  become: yes
  tags: "keycloak:install:setup_file_permissions"

############### Setup admin user
- name: "Task block: Setup admin user"
  block:
  - name: Remove file (delete file if exists)
    file:
      path: "{{ keycloak_home }}/standalone/configuration/keycloak-add-user.json"
      state: absent
  - name: Create admin user
    shell: "{{ keycloak_home }}/bin/add-user-keycloak.sh -u {{ keycloak_admin.user }} -p {{ keycloak_admin.pass }}"
    args:
      executable: /bin/bash
  become: yes
  tags: "keycloak:install:setup_admin"

#### Setup logcleaner script
- name: "Task block: Setup logcleaner script"
  block:
    - name: "Install the logcleaner script template"
      template:
        owner: "{{ keycloak_service_user }}"
        group: "{{ keycloak_service_user }}"
        mode: 0640
        src: templates/logcleaner.sh.j2
        dest: "{{ keycloak_home }}/logcleaner.sh"
    - name: "Create the cronjob"
      cron:
        name: keycloak logcleaner
        day: "*"
        hour: "0"
        minute: "0"
        user: "{{ keycloak_service_user }}"
        job: "sh {{ keycloak_home }}/logcleaner.sh {{ keycloak_logs_folder }} {{ keycloak_logs_max_days }}"
  become: yes
  tags: "keycloak:install:setup_logcleaner"


### install other plugins

# would loop over block of tasks within install_plugin.yml, but looping on blocks is not allowed in ansible
- name: Install other plugins
  include_tasks: "wildfly/install_plugin.yml"
  when: not keycloak_plugins is undefined
  loop: "{{ lookup('dict', keycloak_plugins, wantlist=True) }}"
  tags: "keycloak:install:plugins"


############### Setup keycloak as a service

- name: "Setup keycloak as a service"
  template:
    owner: root
    group: root
    mode: 0644
    src: templates/keycloak.service.wildfly.j2
    dest: /etc/systemd/system/keycloak.service
  become: yes
  tags: "keycloak:install:setup_sys_service"

- name: "Restart keycloak"
  systemd:
    name: keycloak
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes
  tags: "keycloak:install:restart_sys_service"




