---
- name: Ensure EUGridPMA apt key is installed (Debian)
  apt_key: 
    url: "{{ egi_igtf_repo_key_url }}"
    state: present 
  become: yes

- name: Ensure EGI Trust Anchor repository is included (Debian)
  apt_repository: 
    repo: "deb {{ egi_igtf_repo_url }} egi-igtf {{ egi_igtf_components }}" 
    state: present 
  become: yes

- name: Ensure latest versions of EGI Trust Anchors are installed (Debian)
  apt:
    name: ca-policy-egi-core
    state: latest
    update_cache: yes
  become: yes
