---

- name: Enable required Apache modules (Debian)
  apache2_module: 
    state: present
    name: "{{ item }}"
  with_items: "{{ apache_mods_enabled }}"
  become: yes
  notify:
    - restart apache

- name: Disable unnecessary Apache modules (Debian)
  apache2_module: 
    state: absent 
    name: "{{ item }}"
  with_items: "{{ apache_mods_disabled }}"
  become: yes
  notify:
    - restart apache

- name: Remove default vhost from sites-enabled (Debian)
  file:
    path: "{{ apache_conf_path }}/sites-enabled/{{ apache_default_vhost_filename }}"
    state: absent
  become: yes
  notify: restart apache
  when: apache_remove_default_vhost

- name: Configure Apache ports (Debian)
  template:
    src: "ports.conf.j2"
    dest: "{{ apache_conf_path }}/ports.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes
  notify: restart apache

- name: Configure Apache security settings (Debian)
  template:
    src: "security.conf.j2"
    dest: "{{ apache_conf_path }}/conf-available/security.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes
  notify: restart apache

- name: Enable Apache security configuration (Debian)
  file:
    src: "{{ apache_conf_path }}/conf-available/security.conf"
    dest: "{{ apache_conf_path }}/conf-enabled/security.conf"
    state: link
  become: yes
  notify: restart apache

- name: Add Apache vhosts configuration (Debian)
  template:
    src: "vhosts.conf.j2"
    dest: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes
  notify: restart apache
  when: apache_create_vhosts

- name: Enable Apache vhosts configuration (Debian)
  file:
    src: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ apache_vhosts_filename }}"
    state: link
  become: yes
  notify: restart apache
  when: apache_create_vhosts
