# file: fedregagents.yml
#
---

- hosts: fedregistryagent
  #roles:
  #  - { role: fedreg-agent }
  vars:
    rciam_fedreg_agents:
      - name: rciam-fedreg-agent
        path: /srv/rciam-fedreg-agent
        repo: https://github.com/rciam/rciam-service-registry-agent.git
        version: devel
        user:
          name: rciam-fedreg-agent
          group: rciam-fedreg-agent
          gecos: "RCIAM Federation Registry Agent,,,"
          shell: /bin/bash
        cron:
          job: "/srv/rciam-fedreg-agent/.venv/bin/deployer_ssp -c /srv/rciam-fedreg-agent/config.json"
        #  #minute:
        #  #hour:
        #  #day:
        #  #month:
        
  tasks:
    - name: Ensure RCIAM Federation Registry Agent dependencies are installed
      apt:
        name:
          - git
          - python3-venv
        state: present
        install_recommends: no
        update_cache: yes
        cache_valid_time: 86400
      become: yes

    - name: Ensure RCIAM Federation Registry Agent groups exist
      group:
        name: "{{ item.user.group }}"
        system: yes
      loop: "{{ rciam_fedreg_agents }}"
      become: yes

    - name: Ensure RCIAM Federation Registry Agent users exist
      user:
        name: "{{ item.user.name }}"
        groups: "{{ item.user.group }}"
        comment: "{{ item.user.gecos }}" 
        shell: "{{ item.user.shell }}"
        home: "{{ item.path }}"
        system: yes
        create_home: yes
        skeleton: "/empty"
      loop: "{{ rciam_fedreg_agents }}"
      become: yes

    - name: Ensure RCIAM Federation Registry Agent code checkouts are up-to-date
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.path }}"
        version: "{{ item.version }}"
      loop: "{{ rciam_fedreg_agents }}"
      become: yes
      become_user: "{{ item.user.name }}"

    - name: Ensure RCIAM Federation Registry Agent python requirements are installed in virtualenvs
      pip:
        requirements: "{{ item.path }}/requirements.txt"
        virtualenv: "{{ item.path }}/.venv"
        virtualenv_command: python3 -m venv
      loop: "{{ rciam_fedreg_agents }}"
      become: yes
      become_user: "{{ item.user.name }}"
      ignore_errors: yes

    - name: Ensure RCIAM Federation Registry Agents are configured
      template:
        src: "{{ playbook_dir }}/templates/{{ item.name }}/config.json.j2"
        dest: "{{ item.path }}/config.json"
        owner: "{{ item.user.name }}"
        group: "{{ item.user.group }}"
        mode: 0400
        backup: yes
      loop: "{{ rciam_fedreg_agents }}"
      become: yes

    - name: Ensure RCIAM Federation Registry Agent cron jobs are installed
      cron:
        name: "{{ item.name }}"
        user: "{{ item.user.name | default('root') }}"
        cron_file: "{{ item.name }}"
        job: "{{ item.cron.job }}"
        minute: "{{ item.cron.minute | default(omit) }}"
        hour: "{{ item.cron.hour | default(omit) }}"
        day: "{{ item.cron.day | default(omit) }}"
        month: "{{ item.cron.month | default(omit) }}"
      loop: "{{ rciam_fedreg_agents }}"
      when: item.cron is defined
      become: yes
