# file: registryservers.yml
#
---

- hosts: registry
  roles:
    - { role: apache, tags: apache }
    - { role: php, tags: php }
    - { role: shibboleth-sp, tags: shibboleth-sp }
    - { role: comanage-registry, tags: comanage-registry }
    #- cm-role-ui
