# file: utilservers.yml
#
---

- hosts: util
  #roles:
  #  - { role: rciam-util }
  vars:
    rciam_utils:
      - name: rciam-sync-opsportal
        path: /srv/rciam-sync-opsportal
        repo: https://github.com/rciam/rciam-sync-opsportal.git
        version: devel
        user:
          name: rciam-opsportal-client
          group: rciam-opsportal-client
          gecos: "RCIAM Operations Portal Client,,,"
          shell: /bin/bash
        cron:
          job: "/srv/rciam-sync-opsportal/.venv/bin/python /srv/rciam-sync-opsportal/main.py"
          minute: 55
          hour: "*/2"
          #day:
          #month:
      - name: rciam-sync-client-names
        path: /srv/rciam-sync-client-names
        repo: https://github.com/rciam/rciam-sync-client-names.git
        version: v1.0.0
        user:
          name: rciam-client-name-sync
          group: rciam-client-name-sync
          gecos: "RCIAM Client Name Syncer,,,"
          shell: /bin/bash
        cron:
          job: "/srv/rciam-sync-client-names/.venv/bin/python /srv/rciam-sync-client-names/main.py"
          minute: 5
          #hour:
          #day:
          #month:
      - name: rciam-sync-voms
        path: /srv/rciam-sync-voms
        repo: https://github.com/rciam/rciam-sync-voms.git
        version: devel
        user:
          name: rciam-voms-client
          group: rciam-voms-client
          gecos: "RCIAM VOMS Admin Client,,,"
          shell: /bin/bash
        cron:
          job: "/srv/rciam-sync-voms/.venv/bin/python /srv/rciam-sync-voms/main.py"
          minute: "20,50"
          #hour:
          #day:
          #month:
      - name: rciam-expire-vomembers
        path: /srv/rciam-expire-vomembers
        repo: https://github.com/NicolasLiampotis/rciam-expire-vomembers.git
        version: devel
        user:
          name: rciam-registry-client
          group: rciam-registry-client
          gecos: "RCIAM COmanage Registry DB Client,,,"
          shell: /bin/bash
        cron:
          job: "/srv/rciam-expire-vomembers/.venv/bin/python /srv/rciam-expire-vomembers/main.py"
          minute: "29,59"
          #hour:
          #day:
          #month:
        
  tasks:
    - name: Ensure util dependencies are installed
      apt:
        name:
          - git
          - python3-venv
        state: present
        install_recommends: no
        update_cache: yes
        cache_valid_time: 86400
      become: yes

    - name: Ensure util groups exist
      group:
        name: "{{ item.user.group }}"
        system: yes
      loop: "{{ rciam_utils }}"
      become: yes

    - name: Ensure util users exist
      user:
        name: "{{ item.user.name }}"
        groups: "{{ item.user.group }}"
        comment: "{{ item.user.gecos }}" 
        shell: "{{ item.user.shell }}"
        home: "{{ item.path }}"
        system: yes
        create_home: yes
        skeleton: "/empty"
      loop: "{{ rciam_utils }}"
      become: yes

    - name: Ensure util code checkouts are up-to-date
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.path }}"
        version: "{{ item.version }}"
      loop: "{{ rciam_utils }}"
      become: yes
      become_user: "{{ item.user.name }}"

    - name: Ensure util python requirements are installed in virtualenvs
      pip:
        requirements: "{{ item.path }}/requirements.txt"
        virtualenv: "{{ item.path }}/.venv"
        virtualenv_command: python3 -m venv
      loop: "{{ rciam_utils }}"
      become: yes
      become_user: "{{ item.user.name }}"

    - name: Ensure utils are configured
      template:
        src: "{{ playbook_dir }}/templates/{{ item.name }}/config.py.j2"
        dest: "{{ item.path }}/config.py"
        owner: "{{ item.user.name }}"
        group: "{{ item.user.group }}"
        mode: 0400
        backup: yes
      loop: "{{ rciam_utils }}"
      become: yes

    - name: Ensure util cron jobs are installed
      cron:
        name: "{{ item.name }}"
        user: "{{ item.user.name | default('root') }}"
        cron_file: "{{ item.name }}"
        job: "{{ item.cron.job }}"
        minute: "{{ item.cron.minute | default(omit) }}"
        hour: "{{ item.cron.hour | default(omit) }}"
        day: "{{ item.cron.day | default(omit) }}"
        month: "{{ item.cron.month | default(omit) }}"
      loop: "{{ rciam_utils }}"
      when: item.cron is defined
      become: yes
