# file: webproxyservers.yml
#
---

- hosts: webproxy
  roles:
    - { role: rsyslog-pgsql, tags: [rsyslog-pgsql, nginx] }
    - { role: nginx, tags: nginx }
  tasks:
    - name: Set Maintenance Locations
      set_fact:
        maintenance_locations: "['roles','registry','oidc','proxy']"
      tags:
        - nginx:maintenance_on
        - nginx:maintenance_off
        - never
    - name: Enter Maintenance Mode
      copy:
        content: ""
        dest: "/var/www/html/{{ item }}.maintenance.enable"
        force: no
        owner: root
        mode: 0644
      loop: "{{ maintenance | default(maintenance_locations) | default([]) }}"
      loop_control:
        label: "Add control file for Maintenance Mode {{ item }}"
      become: yes
      ignore_errors: yes
      tags:
        - nginx:maintenance_on
        - never
    - name: Exit Maintenance Mode
      file:
        path: "/var/www/html/{{ item }}.maintenance.enable"
        state: absent
      loop: "{{ maintenance_locations | default([]) }}"
      loop_control:
        label: "Removing control file for Maintenance Mode {{ item }}"
      become: yes
      ignore_errors: yes
      tags:
        - nginx:maintenance_off
        - never