---

- name: Configure COmanage Registry database schema
  shell: Console/cake database
  args:
    chdir: "{{ comanage_path }}/app"
  become: yes
  become_user: "{{ comanage_webserver_user }}"
  tags:
    - comanage-registry:init:db

- name: Configure COmanage Registry platform admin and org identity pooling
  shell: Console/cake setup --admin-given-name "{{ comanage_admin.given_name }}" --admin-family-name "{{ comanage_admin.family_name }}" --admin-username "{{ comanage_admin.username }}" --enable-pooling={{ comanage_org_identity_pooling }}
  args:
    chdir: "{{ comanage_path }}/app"
  become: yes
  tags:
    - comanage-registry:init:admin