---

- name: Ensure Shibboleth SP SSL certificate is copied
  copy:
    content: '{{ item.content }}'
    dest: "{{ item.dest }}"
    owner: "{{ shibboleth_sp_user }}"
    group: "{{ shibboleth_sp_group }}"
    mode: "{{ item.mode }}"
  with_items:
    - content: "{{ shibboleth_sp_ssl_cert }}"
      dest: "{{ shibboleth_sp_conf_path }}/cert/sp-crt.pem"
      mode: "0644"
    - content: "{{ shibboleth_sp_ssl_cert_key }}"
      dest: "{{ shibboleth_sp_conf_path }}/cert/sp-key.pem"
      mode: "0600"
  when: shibboleth_sp_ssl_cert_generate|bool == False
  become: yes
  no_log: yes
  notify:
    - Restart Shibboleth SP

- name: Ensure Shibboleth SP self-signed certificate is generated
  command: openssl req -newkey rsa:2048 -new -x509 -days 3652 -subj "{{ shibboleth_sp_ssl_cert_subj }}" -nodes -out sp-crt.pem -keyout sp-key.pem
  args:
    chdir: "{{ shibboleth_sp_conf_path }}/cert"
    creates: "{{ shibboleth_sp_conf_path }}/cert/sp-key.pem"
  when: shibboleth_sp_ssl_cert_generate|bool == True
  become: yes
  notify:
    - Restart Shibboleth SP

- name: Ensure Shibboleth SP certificate is installed
  file:
    state: file
    path: "{{ item.path }}"
    owner: "{{ shibboleth_sp_user }}"
    group: "{{ shibboleth_sp_group }}"
    mode: "{{ item.mode }}"
  with_items:
    - path: "{{ shibboleth_sp_conf_path }}/cert/sp-crt.pem"
      mode: "0644"
    - path: "{{ shibboleth_sp_conf_path }}/cert/sp-key.pem"
      mode: "0600"
  become: yes

- name: Configure Shibboleth SP main settings
  template:
    src: "shibboleth2.xml.j2"
    dest: "{{ shibboleth_sp_conf_path }}/shibboleth2.xml"
    owner: "root"
    group: "root"
    mode: 0644
    backup: yes
  become: yes
  notify:
    - Restart Shibboleth SP

- name: Configure Shibboleth SP attribute mappings
  copy:
    src: "{{ shibboleth_sp_attribute_map_file }}"
    dest: "{{ shibboleth_sp_conf_path }}/attribute-map.xml"
    owner: "root"
    group: "root"
    mode: 0644
    backup: yes
  when: shibboleth_sp_attribute_map_file is defined
  become: yes
  notify:
    - Restart Shibboleth SP

- name: Configure Shibboleth SP attribute policies
  copy:
    src: "{{ shibboleth_sp_attribute_policy_file }}"
    dest: "{{ shibboleth_sp_conf_path }}/attribute-policy.xml"
    owner: "root"
    group: "root"
    mode: 0644
    backup: yes
  when: shibboleth_sp_attribute_policy_file is defined
  become: yes
  notify:
    - Restart Shibboleth SP
