# file: tasks/main.yml
#
---

# Include OS-specific installation tasks
- include: install-Debian.yml
  when: ansible_os_family == 'Debian'
#- include: install-RedHat.yml
#  when: ansible_os_family == 'RedHat'
  tags:
    - install
    - rciam_utils:install

# Include OS-independent installation tasks
- include: install-common.yml
  tags:
    - install
    - rciam_utils:install

# Include OS-independent configuration tasks
- include: configure.yml
  tags:
    - config
    - rciam_utils:config
