# file: tasks/configure.yml
---
- name: Configure webapp
  template:
    src: "{{ item.src_config_path }}"
    dest: "{{ item.dest_config_path }}"
    backup: yes
  loop: "{{ rciam_oidc_clients }}"
  become: yes
