---

- name: Update package cache (Debian)
  apt: update_cache=yes cache_valid_time=86400
  become: yes

- name: Ensure latest CA certificates are installed (Debian)
  apt: pkg=ca-certificates state=latest install_recommends=no
  become: true

- name: Ensure SSP cron module dependencies are installed (Debian)
  apt:
    pkg: "{{ ssp_mod_cron_deps }}"
    state: present
    install_recommends: no
  when: "'cron' in ssp_mods_enabled"
  become: true

#- name: Ensure memcached dependencies are installed (Debian)
#  apt: pkg={{ item }} state=present install_recommends=no
#  with_items: "{{ ssp_memcache_deps }}"
#  when: "ssp_store_type is defined and ssp_store_type == 'memcache'"
#  become: true
#  notify:
#    - restart webserver
