---

# Install OS-specific packages
- include: install-Debian.yml
  when: ansible_os_family == 'Debian'
#- include: install-CentOS.yml
#  when: ansible_os_family == 'CentOS'

# Run OS-independent installation tasks
- include: install-common.yml

# Apply OS-independent configuration
- include: configure-common.yml
