---
- name: Remove pgsql.conf file if exists
  file:
    path: "{{ rsyslogd_path }}/pgsql.conf"
    state: absent
  become: yes
  when: rsyslog_pgsql_enable_logs == true

- name: Ensure /dev/xconsole exists
  ansible.builtin.file:
    path: /dev/xconsole
    state: touch
    owner: syslog
    group: adm
    mode: u=rw,g=rw,o=r
  when: rsyslog_pgsql_enable_logs == true
  become: yes

- name: Ensure rsyslog for nginx logs is configured
  template:
    src: rsyslogd-nginx-{{ ansible_os_family }}.conf.j2
    dest: "{{ rsyslogd_path }}/51-nginx.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes
  notify: Restart rsyslog
  when: rsyslog_pgsql_enable_logs == true
