---

- name: "Install {{ item[1].providerId }} key with name '{{ item[1].name }}'"
  uri:
    url: "https://{{ keycloak_proxy_host }}/auth/admin/realms/{{ item[0].name }}/components"
    method: POST
    body_format: json
    headers:
      Authorization: "Bearer {{ result.json.access_token }}"
    body:
      name: "{{ item[1].name }}"
      providerId: "{{ item[1].providerId }}"
      providerType: org.keycloak.keys.KeyProvider
      parentId: "{{ item[0].name }}"
      config: "{{ item[1].config }}"
    status_code: 201
