---

- name: "Configuring IdP: {{item[1].alias}} Get current IdPs list for realm: {{item[0].name}}"
  include_tasks: blocks/helpers/get_realm_idps_list.yml

- name: "Add idp: {{ item[1].alias }}"
  uri:
    url: "https://{{ keycloak_proxy_host }}/auth/admin/realms/{{ item[0].name }}/identity-provider/instances"
    method: POST
    body_format: json
    headers:
      Authorization: "Bearer {{ result.json.access_token }}"
    body:
      "{{item[1]}}"
    status_code: 201
  when: "item[1].alias not in idps_list"