---
- block:
    - uri:
        url: "http://localhost:8080/{{ keycloak_base_url_path }}"
        method: GET
      register: welcome_page_resp

    - set_fact:
        welcome_page_cookies: "{{ welcome_page_resp.cookies_string }}"

    # welcome_page_cookies should have a value: 'WELCOME_STATE_CHECKER=W3nN9JSpzfHZMU5efRYXqtX_J69cU8qlSuwWD47kcdY'

    - name: Setup admin user
      uri:
        url: "http://localhost:8080/{{ keycloak_base_url_path }}"
        method: POST
        body_format: form-urlencoded
        headers:
          Cookie: "{{ welcome_page_cookies }}"
        body:
          username: "{{ keycloak_admin.user }}"
          password: "{{ keycloak_admin.pass }}"
          passwordConfirmation: "{{ keycloak_admin.pass }}"
          stateChecker: "{{ welcome_page_cookies.split('=') | last }}"
        status_code: [200]

  run_once: true