---

- name: "Get current list of federations of the realm: {{item[0].name}}"
  include_tasks: blocks/helpers/get_realm_federations.yml

- set_fact:
    federation_exists: "{{realm_federation_matches | length > 0 }}"

- set_fact:
    additional_info:
      internalId: "{{realm_federation_matches[0].internalId}}"
  when: federation_exists

- set_fact:
    body: "{{ item[1] | combine(additional_info , recursive=True ) }}"
  when: federation_exists

- set_fact:
    body: "{{ item[1] }}"
  when: not federation_exists


- name: "Configuring federation: {{item[1].alias}}"
  block:

    - name: "Configuring federation {{ item[1].alias }}"
      uri:
        url: "https://{{ keycloak_proxy_host }}/auth/admin/realms/{{ item[0].name }}/identity-provider-federation/instances"
        method: POST
        body_format: json
        headers:
          Authorization: "Bearer {{ result.json.access_token }}"
        body:
          "{{body}}"
        status_code: 201

