---

- name: "Get current IdPs list of realm: {{item[0].name}}"
  include_tasks: blocks/helpers/get_realm_idps_list.yml

- name: "Installing saml IdP: {{item[1].data.alias}}"
  block:
    - name: "Get config from url: {{ item[1].metadataUrl }}"
      uri:
        url: "https://{{ keycloak_proxy_host }}/auth/admin/realms/{{ item[0].name }}/identity-provider/import-config"
        method: POST
        body_format: json
        headers:
          Authorization: "Bearer {{ result.json.access_token }}"
        body:
          fromUrl: "{{ item[1].metadataUrl }}"
          providerId: "saml"
        status_code: 200
      register: saml_idp_result

    - name: "Setup saml IdP {{ item[1].data.alias }}"
      uri:
        url: "https://{{ keycloak_proxy_host }}/auth/admin/realms/{{ item[0].name }}/identity-provider/instances"
        method: POST
        body_format: json
        headers:
          Authorization: "Bearer {{ result.json.access_token }}"
        body:
          "{{ { 'config': saml_idp_result.json } | combine( item[1].data, recursive=True ) }}"
        status_code: 201
  when: "item[1].data.alias not in idps_list"