---

- name: Start keycloak
  systemd:
    name: keycloak
    state: started
  become: yes

- name: Stop keycloak
  systemd:
    name: keycloak
    state: stopped
  become: yes

- name: Restart keycloak
  systemd:
    name: keycloak
    state: restarted
  become: yes

- name: Reload systemd daemon
  systemd:
    name: keycloak
    state: restarted
    daemon_reload: yes
  become: yes
