---

  - name: Install dependencies
    apt:
      pkg:
        - curl
        - git
        - nginx

  - name: Add node repository
    shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
    args:
      warn: no

  - name: Install node and npm
    apt:
      pkg:
        - build-essential
        - nodejs
        - npm


  - name: Debug PATH and npm location
    debug:
      var: ansible_env.PATH
  - name: Debug npm location
    shell: which npm
    register: npm_location
    changed_when: false
  - debug:
      var: npm_location.stdout

  - name: Install pm2
    npm:
        name: pm2
        global: yes


