---

- name: Define PostgreSQL python module version (Ubuntu)
  set_fact:
    postgresql_psycopg2_package: "{{ postgresql_default_psycopg2_package }}"
  when: postgresql_psycopg2_package is not defined
  tags:
    - always

- name: Ensure PostgreSQL python module is installed (Ubuntu)
  apt:
    name: "{{ postgresql_psycopg2_package }}"
    state: present
    install_recommends: no
    update_cache: yes
    cache_valid_time: 86400
  become: yes