---
- name: "Get list of keys of realm: {{ item[0].name }}"
  uri:
    url: "{{ keycloak_proxy_host }}/admin/realms/{{ item[0].name }}/components?parent=demo&type=org.keycloak.keys.KeyProvider"
    method: GET
    headers:
      Authorization: "Bearer {{ tokens.json.access_token }}"
    status_code: 200
  register: "keys_result"

- set_fact:
    keys_descr_list: "{{ keys_result.json | to_json | from_json | json_query(keys_query)}}"
  vars:
    keys_query: "[].join(':',[providerId, name])"

