---

- name: Acquire tokens
  uri:
    url: https://{{ keycloak_proxy_host }}/auth/realms/master/protocol/openid-connect/token
    method: POST
    body_format: form-urlencoded
    body:
      client_id: "admin-cli"
      username: "{{keycloak_admin.user}}"
      password: "{{keycloak_admin.pass}}"
      grant_type: "password"
  register: "tokens"    # token is in "tokens.json.access_token"
