---

- name: "Search federation {{item[1].alias}} in keycloak"
  uri:
    url: "{{ keycloak_proxy_host }}/admin/realms/{{ item[0].name }}"
    method: GET
    headers:
      Authorization: "Bearer {{ tokens.json.access_token }}"
    status_code: 200
  register: "realm_result"

- set_fact:
    realm_federation_matches: "{{realm_result.json.identityProvidersFederations | json_query(query) | default([]) }}"
  vars:
    query: '[?alias == `{{ item[1].alias }}` ].{alias: alias, internalId: internalId }'

