---

- include_tasks: blocks/helpers/get_tokens.yml

- name: "Clear {{ current_default_default.name }} from the default default client scopes list"
  uri:
    url: "{{ keycloak_proxy_host }}/admin/realms/{{ current_realm.name }}/default-default-client-scopes/{{ current_default_default.id }}"
    method: "DELETE"
    headers:
      Authorization: "Bearer {{ tokens.json.access_token }}"
    status_code: "204"