---

- name: Update package cache (Debian)
  apt: update_cache=yes cache_valid_time=86400
  become: yes

- name: Ensure dirmngr is installed (Debian)
  apt: name={{ item }} state=present install_recommends=no
  with_items:
    - dirmngr
  become: yes
