# file: tomcat/tasks/deploy-webapp.yml
#
---
- name: Get GitHub asset ID of WAR file
  script: "{{ inventory_dir }}/files/get_gh_asset_id.sh {{ webapp_github_repo }} {{ webapp_github_repo_token }} {{ webapp_github_release_version }} {{ webapp_github_release_file }}"
  register: github_asset_id

- name: Ensure WAR file is downloaded
  command: wget -q --auth-no-challenge --header="Accept:application/octet-stream" "https://{{ webapp_github_repo_token }}:@api.github.com/repos/{{ webapp_github_repo }}/releases/assets/{{ github_asset_id.stdout }}" -O "{{ webapp_file }}_{{ webapp_github_release_version }}"
  args:
    chdir: "{{ webapp_download_path }}/"
    creates: "{{ webapp_file }}_{{ webapp_github_release_version }}"
  become: true

- name: Check that WAR file has been deployed
  stat:
    path: "{{ webapp_path }}/{{ webapp_file }}"
  register: webapp_file_status
  become: true

- name: Deploy WAR file when WAR file has not been deployed
  copy:
    src: "{{ webapp_download_path }}/{{ webapp_file }}_{{ webapp_github_release_version }}"
    dest: "{{ webapp_path }}/{{ webapp_file }}"
    remote_src: true
  when: webapp_file_status.stat.exists == False
  become: true

- name: Calculate checksum of deployed WAR file
  stat:
    path: "{{ webapp_path }}/{{ webapp_file }}"
    checksum_algorithm: sha256
    get_checksum: true
  register: webapp_file_checksum_old
  when: webapp_file_status.stat.exists == True
  become: true

- name: Calculate checksum of downloaded WAR file
  stat:
    path: "{{ webapp_download_path }}/{{ webapp_file }}_{{ webapp_github_release_version }}"
    checksum_algorithm: sha256
    get_checksum: true
  register: webapp_file_checksum_new
  when: webapp_file_status.stat.exists == True
  become: true

- name: Ensure Tomcat is stopped
  service:
    name: "{{ tomcat_service }}"
    state: "stopped"
  when: webapp_file_status.stat.exists == True and webapp_file_checksum_old.stat.checksum != webapp_file_checksum_new.stat.checksum
  become: true

- name: Ensure previous WAR file is deleted
  file:
    path: "{{ webapp_path }}/{{ webapp_file }}"
    state: absent
  when: webapp_file_status.stat.exists == True and webapp_file_checksum_old.stat.checksum != webapp_file_checksum_new.stat.checksum
  become: true

- name: Ensure previous WAR directory is deleted
  file:
    path: "{{ webapp_path }}/{{ webapp_context_path }}"
    state: absent
  when: webapp_file_status.stat.exists == True and webapp_file_checksum_old.stat.checksum != webapp_file_checksum_new.stat.checksum
  become: true

- name: Deploy new version of WAR file
  copy:
    src: "{{ webapp_download_path }}/{{ webapp_file }}_{{ webapp_github_release_version }}"
    dest: "{{ webapp_path }}/{{ webapp_file }}"
    remote_src: true
  when: webapp_file_status.stat.exists == True and webapp_file_checksum_old.stat.checksum != webapp_file_checksum_new.stat.checksum
  become: true

- name: Ensure Tomcat is started
  service:
    name: "{{ tomcat_service }}"
    state: "started"
  when: webapp_file_status.stat.exists == True and webapp_file_checksum_old.stat.checksum != webapp_file_checksum_new.stat.checksum
  become: true
