# file: tomcat/tasks/install-Debian.yml
#
---

- name: Ensure Tomcat is installed (Debian)
  apt:
    name: "tomcat{{ tomcat_version }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
    install_recommends: no
  become: yes
