---

- name: Install git if it is not present
  apt:
    name: git
    state: present
    update_cache: yes
  become: yes

- name: Clear cache of COmanage
  command: su {{ comanage_registry_plugins_webuser }} -s /bin/sh -c ./Console/clearcache
  args:
    chdir: "{{ comanage_path }}/app"
  become: yes