---

- name: Update package cache (Debian)
  apt: 
    update_cache: yes 
    cache_valid_time: 86400
  become: yes

- name: Ensure common packages are installed (Debian)
  apt:
    pkg:
      - aptitude
      - ca-certificates
      - vim-nox
    state: present
    install_recommends: no
  become: true
