---

- name: Install apt packages required for alternative PHP repo (Debian)
  apt:
    name: "{{ php_apt_packages }}"
    state: present
    update_cache: yes
  when: php_alt_repo and php_apt_packages is defined and php_apt_packages|length
  become: yes

- name: Install apt key for PHP repo (Debian)
  apt_key:
    url: '{{ php_apt_key }}'
    state: present
  when: php_alt_repo and php_apt_key is defined
  become: yes

- name: Add alternative PHP repo (Debian)
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
    filename: "php"
  loop: "{{ php_apt_repositories }}"
  when: php_alt_repo and php_apt_repositories is defined and php_apt_repositories|length
  become: yes

- name: Ensure PHP packages are installed (Debian)
  apt:
    name: "{{ php_packages }}"
    state: present
    update_cache: yes
    install_recommends: no
  become: yes
  notify:
    - restart webserver

- name: Ensure PHP extensions are installed (Debian)
  apt:
    pkg: "{{ php_extensions }}"
    state: present
    update_cache: yes
    install_recommends: no
  become: yes
  notify:
    - restart webserver
