---

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

# Run OS-specific installation tasks
- include: install-Debian.yml
  when: ansible_os_family == 'Debian'

# Run OS-independent installation tasks
- include: install-common.yml

# Apply OS-independent configuration
- include: configure-common.yml

- name: Ensure memcached service is at selected state and enabled on boot
  service:
    name: memcached
    state: started
    enabled: yes
  become: yes
